# Generated by Django 5.1 on 2024-08-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_alter_amenity_name_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='properties.property')),
            ],
        ),
    ]
