# Generated by Django 5.1 on 2024-08-23 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysummary',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertysummary',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
