# Generated by Django 5.1 on 2024-08-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0002_propertysummary_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertysummary',
            options={'verbose_name': 'Property Summary', 'verbose_name_plural': 'Property Summaries'},
        ),
    ]
